### ISSUE TITLE
Drill file?

### ISSUE THREAD

**Issue by mfalkvidd** [lyusupov/Ebyte-E78-breakout-PCB#1]
Hi.

Thanks a lot for sharing this board. I tried to order it on pcbs.io (using Chrome and Firefox) but it complains that it cannot connect to Paypal.

So I tried to order using the gerber files from dirtypcbs. Dirtypcbs says that the zip archive is missing a drill file (`No drill (.TXT/.DRL/.DRI/.DRD) file found.`)

Do you have a drill file available somewhere?

**Comment by lyusupov** [comment]
There **IS** drill file in there...

You can view the [ZIP file](https://github.com/lyusupov/Ebyte-E78-breakout-PCB/raw/master/gerber/SoftRF-E78-breakout.zip) online at https://www.pcbway.com/project/OnlineGerberViewer.html to make sure that all the layers are present.

![image](https://user-images.githubusercontent.com/5849637/95883597-cca25680-0d83-11eb-9ca8-2f4fbb52001a.png)

.XLN file contains drill information in 'Excellon Drill' format

You may consider to rename .xln into .drl or .dri extension to see if it helps you with your PCB service provider.

**Comment by mfalkvidd** [comment]
Great. Strange that Dirtypcb didn't recognize it. Thank you very much!
