### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by josmanperez** [lyusupov/Ebyte-E78-breakout-PCB#2]
Hello Lyusupov,

First of all, let me say thank you for all the hard work you've made. I want to ask you a few questions (sorry for open an `issue` but I couldn't find another way to send you a message).

I've worked before with the ESP8266 (more precisely the ESP12) modules before. I've made a board to gather sensor data and send that data through a gateway with an Internet connection.  Like this: 
![ESP12 board](https://www.ncbi.nlm.nih.gov/pmc/articles/instance/5375751/bin/sensors-17-00465-g004.jpg) 

The problem with this approach is the low length that could achieve, just a few meters from the gateway. I am testing ESP-NOW to see if I could spread the nodes further away. But the truth is I want to change from ESP WiFi technology to Lorawan. 

I've bought the EBYTE e78-868ln22s, but I don't how to use it. Could I program it through Arduino IDE? or it needs to be programmed through AT commands? Do you know where I could find examples of how to build a pretty easy program with these modules to see how it works?

Thank you so much for your help.

Regards

**Comment by lyusupov** [comment]
This GitHub page is not an educational resource.

You'd better ask your questions on TTN Forum.
This is an example of a thread about the Ebyte E78 nodule:
https://www.thethingsnetwork.org/forum/t/question-to-e78-868ln22s-lorawan-module-asr6501-chip-payload-0-bytes/38640

**Comment by josmanperez** [comment]
Hello Lyusupov,

Thank you for your answer. I've tried to buy the PCB board in pcb.io but it didn't work when trying to checkout (with both PayPal or credit card).

I'll contact them. Just for you to know. 

Again, thank you!
