### ISSUE TITLE
E78 SWD access using ktiprog 2

### ISSUE THREAD

**Issue by krzysztofkuczek** [lyusupov/Ebyte-E78-breakout-PCB#3]
Hi,
First of all thank you for your great design.
I'm starting with ASR6501 development, to port my RC control system to E78 modules, and I'm not very familiar with cypress mcus, so maybe i do something wrong, but my E78-868LN22S seems to be not accessible using SWD kitprog2 device. 
Do you have any experience with such a strange behaviour, maybe some batches are protected by kiling SWD interface...
Thank you in advance
Kris

**Comment by lyusupov** [comment]
https://www.thethingsnetwork.org/forum/t/breakout-board-for-ebyte-e78-asr6501-mcu-lora-module/38722

**Comment by krzysztofkuczek** [comment]
Thank you very much, looks like kitprog 3 is required...
